### 1. PytorchTensor Base

#### 1.1 torch.tensor

In [1]:
import torch

for module in torch,:
    print(module.__name__, module.__version__)

torch 1.9.1+cpu


In [2]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.type())

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.LongTensor


#### 1.2 torch.Tensor

In [3]:
# 不指定数据, 会随机生成数据
b = torch.Tensor(2, 2)
print(b)

tensor([[8.4490e-39, 1.0469e-38],
        [9.8265e-39, 9.4591e-39]])


In [4]:
# 使用tuple创建
d = torch.tensor(((1, 2), (3, 4)))
print(d.type())
print(d.type_as(a))

torch.LongTensor
tensor([[1, 2],
        [3, 4]])


#### 1.3 torch.empty

In [5]:
d = torch.empty(2, 3)
print(d)
print(d.type())
print(d.type_as(a))

tensor([[8.4257e-07, 3.1948e+21, 2.1762e-04],
        [5.2356e+22, 5.1203e-11, 4.2330e+21]])
torch.FloatTensor
tensor([[                   0, -9223372036854775808,                    0],
        [-9223372036854775808,                    0, -9223372036854775808]])


#### 1.4 torch.zeros

In [6]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
d = torch.zeros(2, 3)
print(d.type())
# 将 d 的类型转换为 tensor a的类型
print(d.type_as(a).type())

torch.FloatTensor
torch.LongTensor


#### 1.5 torch.zeros_like
- 将已有的tensor变成全0

In [7]:
d = torch.Tensor(2, 3)
print(d)
d = torch.zeros_like(d)
print(d)
print(d.type())

tensor([[2.0313e+20, 1.0131e-11, 2.0568e+20],
        [8.3748e-10, 8.4257e-07, 3.1948e+21]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


#### 1.6 torch.eye

- 生成对角相同的数据

In [8]:
d = torch.eye(2, 2)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[1, 0],
        [0, 1]])


#### 1.7 torch.ones

- 生成全是1的tensor

In [9]:
d = torch.ones(2, 2)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[1, 1],
        [1, 1]])


#### 1.8 torch.ones_like

- 将已有的数据转换为全是1的tensor

In [10]:
d = torch.tensor([1, 2, 3])
d = torch.ones_like(d)
print(d.type())
print(d.type_as(a))

torch.LongTensor
tensor([1, 1, 1])


#### 1.9 torch.rand

- 生成指定shape的随机数(0~1)

In [15]:
d = torch.rand(2, 3)
print(d.type())
print(d)

torch.FloatTensor
tensor([[0.0885, 0.3703, 0.6083],
        [0.4286, 0.2500, 0.1635]])


#### 1.10 torch.arange

- 生成指定范围(步长)的数据
- arange(start, end, step)

In [16]:
d = torch.arange(2, 10, 2)
print(d.type())
print(d.type_as(a))

torch.LongTensor
tensor([2, 4, 6, 8])


#### 1.11 torch.linspace

- 生成等间隔的数据
- linspace(start, end, step)

In [18]:
d = torch.linspace(10, 2, 3)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([10,  6,  2])


#### 1.12 torch.normal

- 生成正态分布的数据
- normal(mean=均值, std=方差, size=(2, 3), out=输出到指定tensor)

In [20]:
dd = torch.normal(mean=0, std=1, size=(2, 3), out=b)
print(b)
print(dd)

tensor([[ 0.9532,  1.3133,  0.1970],
        [-1.6926, -1.0456,  0.4540]])
tensor([[ 0.9532,  1.3133,  0.1970],
        [-1.6926, -1.0456,  0.4540]])


In [22]:
d = torch.normal(mean=torch.rand(5), std=torch.rand(5))
print(d.type())
print(d)

torch.FloatTensor
tensor([ 0.2966,  0.5222,  1.6873, -0.8415,  1.6234])


#### 1.13 tensor.uniform_

- 生成均匀分布的数据
- uniform_(-1, 1) : 生成-1 到 1 之间均匀分布的数据

In [26]:
d = torch.Tensor(2, 2)
print(d)
print(d.uniform_(-1, 1))
print(d.type())

tensor([[1.4013e-45,        nan],
        [7.3607e-33, 4.5915e-41]])
tensor([[ 0.1362, -0.1488],
        [-0.1569, -0.1930]])
torch.FloatTensor


#### 1.14 torch.randperm

- 随机打乱指定的数据

In [28]:
d = torch.randperm(10)
print(d.type())
print(d.type_as(a))

torch.LongTensor
tensor([5, 9, 6, 0, 1, 2, 8, 3, 4, 7])


### 2. Tensor Property

- 每一个Tensor有torch.dtype、torch.device、torch.layout三种属性。
    1. device : 表示GPU的设备, 通常用 conda:0, conda1, ... 表示
    2. torch.device("cpu") 定义将 tensor 放到cpu中
- torch.device标识了torch.Tensor对象在创建之后所存储在的设备名称
- torch.layout表示torch.Tensor内存布局的对象。

#### 2.1 稀疏张量的表示

- torch.sparse_coo_tensor
    1. indices : 坐标 => [[1,2,3], [0,0,0]] = (1,0) (2,0) (3,0)
    2. size : shape
    3. values : 稀疏矩阵值

In [30]:
import torch

# 定义将 tensor 放到cpu中
dev = torch.device("cpu")
# 定义将 tensor 放到Gpu中
# dev = torch.device("cuda")

- 将tensor放到cpu中

In [32]:
a = torch.tensor([2, 2],
                 dtype=torch.float32,
                 device=dev)
print(a)

tensor([2., 2.])


In [45]:
i = torch.tensor([[0, 1, 2, 3], [0, 1, 2, 3]])
v = torch.tensor([1, 2, 3, 4])
a = torch.sparse_coo_tensor(indices=i, values=v, size=(4, 4),
                            dtype=torch.float32,
                            device=dev)
print(a)

tensor(indices=tensor([[0, 1, 2, 3],
                       [0, 1, 2, 3]]),
       values=tensor([1., 2., 3., 4.]),
       size=(4, 4), nnz=4, layout=torch.sparse_coo)


#### 2.2 稀疏矩阵转稠密矩阵

In [44]:
i = torch.tensor([[0, 1, 2], [0, 1, 2]])
v = torch.tensor([1, 2, 3])
a = torch.sparse_coo_tensor(i, v, (4, 4),
                            dtype=torch.float32,
                            device=dev)
print(a.type())
print(a)
# 转稠密矩阵
print(a.to_dense())

torch.sparse.FloatTensor
tensor(indices=tensor([[0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([1., 2., 3.]),
       size=(4, 4), nnz=3, layout=torch.sparse_coo)
tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]])


### 3. Tensor operator

- 本章节介绍Tensor的基本运算

#### 3.1 加法运算

- 加法运算直接返回结果
    - a + b
    - a.add(b)
    - torch.add(a, b)
- 修改原先的值
    - a.add_(b) : 会将a+b的结果直接赋值给a

In [50]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a)
print(b)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [51]:
print(a + b)
print(a.add(b))
print(torch.add(a, b))
print(a)
# 会修改a的值
print(a.add_(b))
print(a)

tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([5, 7, 9])
tensor([1, 2, 3])
tensor([5, 7, 9])
tensor([5, 7, 9])


#### 3.2 减法运算

- 直接返回结果
    - a - b
    - torch.sub(a, b)
    - a.sub(b)
- 将返回结果赋值给变量
    - a.sub_(b) 将计算的结果赋值给a

In [53]:
a = torch.tensor([4,5,6])
b = torch.tensor([1,2,3])

print(a - b)
print(torch.sub(a, b))
print(a.sub(b))
print(a.sub_(b))
print(a)

tensor([3, 3, 3])
tensor([3, 3, 3])
tensor([3, 3, 3])
tensor([3, 3, 3])
tensor([3, 3, 3])


#### 3.3 乘法运算

- 注意 : 对应的值乘以对应的值, 并不是矩阵运算
- 直接返回结果
    1. a * b
    2. torch.mul(a, b)
    3. a.mul(b)
- 将返回的值赋给变量
    1. a.mul_(b) 将结果直接赋值给a


In [56]:
a = torch.tensor([[1,1,1], [2,2,2], [3,3,3]])
b = torch.tensor([[1,1,1], [2,2,2], [3,3,3]])

print(a * b)
print(torch.mul(a, b))
print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

tensor([[1, 1, 1],
        [4, 4, 4],
        [9, 9, 9]])
tensor([[1, 1, 1],
        [4, 4, 4],
        [9, 9, 9]])
tensor([[1, 1, 1],
        [4, 4, 4],
        [9, 9, 9]])
tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[1, 1, 1],
        [4, 4, 4],
        [9, 9, 9]])
tensor([[1, 1, 1],
        [4, 4, 4],
        [9, 9, 9]])


#### 3.4 除法运算

- 直接返回结果
    1. a/b
    2. torch.div(a, b)
    3. a.div(b)
- 将返回结果赋值给指定变量
    1. a.div_(b)

In [59]:
a = torch.tensor([[1,1,1], [2,2,2], [3,3,3]], dtype=torch.float32)
b = torch.tensor([[2,2,2], [2,2,2], [2,2,2]], dtype=torch.float32)

print(a/b)
print(torch.div(a, b))
print(a.div(b))
print(a.div_(b))
print(a)

tensor([[0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000],
        [1.5000, 1.5000, 1.5000]])
tensor([[0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000],
        [1.5000, 1.5000, 1.5000]])
tensor([[0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000],
        [1.5000, 1.5000, 1.5000]])
tensor([[0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000],
        [1.5000, 1.5000, 1.5000]])
tensor([[0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000],
        [1.5000, 1.5000, 1.5000]])


#### 3.5 矩阵运算

- 返回计算结果
    1. a @ b
    2. a.matmul(b)
    3. torch.matmul(a, b)
    4. torch.mm(a, b)
    5. a.mm(b)

In [63]:
a = torch.tensor([[1,1], [2,2]])
b = torch.tensor([[1,1], [2,2]])

# [1,1] * [1,2] = 3, [2,2] * [1,2] = 6
print(a @ b)
print(a.matmul(b))
print(torch.matmul(a, b))
print(torch.mm(a, b))
print(a.mm(b))

tensor([[3, 3],
        [6, 6]])
tensor([[3, 3],
        [6, 6]])
tensor([[3, 3],
        [6, 6]])
tensor([[3, 3],
        [6, 6]])
tensor([[3, 3],
        [6, 6]])


#### 3.6 高维tensor计算

In [64]:
# 四维向量
a = torch.ones(1, 2, 3, 4)
b = torch.ones(1, 2, 4, 3)
print(a.matmul(b).shape)

torch.Size([1, 2, 3, 3])


#### 3.7 torch.pow

- pow(var, n) 计算var的n次方
- 直接返回结果
    1. torch.pow(a, 3)
    2. a.pow(3)
    3. a**3
- a.pow_(3)
    1. 直接返回结果, 然后将结果赋值给变量a

In [65]:
a = torch.tensor([1, 2])
print(torch.pow(a, 3))
print(a.pow(3))
print(a**3)
print(a.pow_(3))
print(a)

tensor([1, 8])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])


#### 3.8 torch.exp

In [66]:
a = torch.tensor([1, 2],
                 dtype=torch.float32)
print(a.type())
print(torch.exp(a))
print(torch.exp_(a))
print(a.exp())
print(a.exp_())

torch.FloatTensor
tensor([2.7183, 7.3891])
tensor([2.7183, 7.3891])
tensor([  15.1543, 1618.1781])
tensor([  15.1543, 1618.1781])


#### 3.9 torch.log

In [67]:
a = torch.tensor([10, 2],
                 dtype=torch.float32)
print(torch.log(a))
print(torch.log_(a))
print(a.log())
print(a.log_())

tensor([2.3026, 0.6931])
tensor([2.3026, 0.6931])
tensor([ 0.8340, -0.3665])
tensor([ 0.8340, -0.3665])


#### 3.10 torch.sqrt

In [68]:
a = torch.tensor([10, 2],
                 dtype=torch.float32)
print(torch.sqrt(a))
print(torch.sqrt_(a))

print(a.sqrt())
print(a.sqrt_())

tensor([3.1623, 1.4142])
tensor([3.1623, 1.4142])
tensor([1.7783, 1.1892])
tensor([1.7783, 1.1892])
