### 1. PytorchTensor Base

#### 1.1 torch.tensor

In [2]:
import torch

for module in torch,:
    print(module.__name__, module.__version__)

torch 1.9.1+cpu


In [3]:
a = torch.tensor([[1,2,3], [4,5,6]])
print(a)
print(a.type())

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.LongTensor


#### 1.2 torch.Tensor

In [4]:
# 不指定数据, 会随机生成数据
b = torch.Tensor(2, 2)
print(b)

tensor([[0., 0.],
        [0., 0.]])


In [8]:
# 使用tuple创建
d = torch.tensor(((1, 2), (3, 4)))
print(d.type())
print(d.type_as(a))

torch.LongTensor
tensor([[1, 2],
        [3, 4]])


#### 1.3 torch.empty

In [9]:
d = torch.empty(2,3)
print(d)
print(d.type())
print(d.type_as(a))

tensor([[0.0000e+00, 0.0000e+00, 8.5018e-07],
        [1.0859e-05, 6.8629e-07, 2.1143e+20]])
torch.FloatTensor
tensor([[                   0,                    0,                    0],
        [                   0,                    0, -9223372036854775808]])


#### 1.4 torch.zeros

In [13]:
a = torch.tensor([[1,2,3], [4,5,6]])
d = torch.zeros(2,3)
print(d.type())
# 将 d 的类型转换为 tensor a的类型
print(d.type_as(a).type())

torch.FloatTensor
torch.LongTensor
torch.FloatTensor


#### 1.5 torch.zeros_like
- 将已有的tensor变成全0

In [14]:
d = torch.Tensor(2,3)
print(d)
d = torch.zeros_like(d)
print(d)
print(d.type())

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 9.0919e-39]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.FloatTensor


#### 1.6 torch.eye

- 生成对角相同的数据

In [16]:
d = torch.eye(2, 2)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[1, 0],
        [0, 1]])


#### 1.7 torch.ones

- 生成全是1的tensor

In [17]:
d = torch.ones(2, 2)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[1, 1],
        [1, 1]])


#### 1.8 torch.ones_like

- 将已有的数据转换为全是1的tensor

In [19]:
d = torch.tensor([1,2,3])
d = torch.ones_like(d)
print(d.type())
print(d.type_as(a))

torch.LongTensor
tensor([1, 1, 1])


#### 1.9 torch.rand

- 生成指定shape的随机数

In [20]:
d = torch.rand(2, 3)
print(d.type())
print(d.type_as(a))

torch.FloatTensor
tensor([[0, 0, 0],
        [0, 0, 0]])
