In [1]:
from gensim.models import Word2Vec
import pandas as pd
import numpy as np

In [2]:
model = Word2Vec.load("../out_dir/word2vec.model")

In [3]:
print(model)

Word2Vec(vocab=201753, vector_size=300, alpha=0.025)


In [5]:
vectors = model.wv
vectors

In [9]:
type(vectors.vectors)

numpy.ndarray

In [11]:
# 201753 * 300 的向量矩阵
vectors.vectors[:5]

array([[-0.07960369,  0.04473848, -0.00677849, ..., -0.09039017,
         0.06436863, -0.08235117],
       [-0.06529462,  0.01508998,  0.01426116, ..., -0.04062453,
         0.03730721, -0.0962921 ],
       [ 0.01403169, -0.02741992, -0.07740057, ...,  0.09647208,
         0.06500885, -0.12682168],
       [-0.0147886 , -0.05948175, -0.05440816, ...,  0.10948094,
         0.06187326, -0.09614369],
       [ 0.01693914, -0.08330592,  0.00353177, ...,  0.09865411,
         0.0311062 , -0.12492971]], dtype=float32)

In [15]:
# 单词词表,
print(vectors.index_to_key[:10])
print(type(vectors.index_to_key))

print(vectors.index_to_key[0])
print(vectors.index_to_key[1])
print(vectors.index_to_key[2])

['[', ']', '/', '@', ':', '泪', '~', '嘻嘻', '#', '爱']
<class 'list'>
[
]
/


In [21]:
# 词袋, 带索引
print(type(vectors.key_to_index))
print(len(vectors.key_to_index))
for key, index in vectors.key_to_index.items():
    if index < 10:
        print(key, index)

<class 'dict'>
201753
[ 0
] 1
/ 2
@ 3
: 4
泪 5
~ 6
嘻嘻 7
# 8
爱 9


In [26]:
# 词表索引顺序和向量表对应
print(vectors['['][:10])
print(vectors.vectors[0][:10])

[-0.07960369  0.04473848 -0.00677849  0.02826606 -0.0536666  -0.02952201
  0.08609938  0.08867253 -0.03245846 -0.04782206]
[-0.07960369  0.04473848 -0.00677849  0.02826606 -0.0536666  -0.02952201
  0.08609938  0.08867253 -0.03245846 -0.04782206]


In [27]:
import torch
from torch import nn


class RNNModel(nn.Module):
    def __init__(self, vectors):
        super().__init__()
        self.embedding = nn.Embedding.from_pretrained(vectors)

    def forward(self, x):
        embed = self.embedding(x)
        return embed

In [28]:
weights = torch.FloatTensor(vectors.vectors)
print(type(weights))

<class 'torch.Tensor'>


In [33]:
rnn_model = RNNModel(weights)
input_tensor = torch.tensor([i for i in range(640)]).reshape([64, 10]) # 生成一个每个句子长度是10, 64行的数据
res = rnn_model.forward(input_tensor)
print(res.size())

torch.Size([64, 10, 300])


In [54]:
data = np.ndarray([3,2])
data

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [66]:
UNK = np.zeros(2)
PAD = np.zeros(2)

new_data = np.vstack((data, UNK, PAD))
new_data

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])